name: Commit Phase
run-name: ${{ github.actor }} is running a pipeline
on: [push]

concurrency: commit_phase

jobs:
  Test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "pretending to run the tests"
      - run: sleep 1m
      - run: echo "pretending to build"
      - run: sleep 1m
  Trigger_Acceptance_Phase:
    needs: [Test_and_build]
    uses: ./.github/workflows/2-acceptance-phase.yml
