name: Acceptance Phase
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_call]

concurrency: testing_environment

jobs:
  Update_Testing_Environment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: sleep 30s
  Run_Acceptance_Tests:
    needs: [Update_Testing_Environment]
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: sleep 5m
