name: Acceptance Phase
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch, workflow_call]

concurrency: testing_environment

jobs:
  Update Testing Environment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  Run Acceptance Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
